import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
from Backend.Koch import *
from Backend.SendData import *
from Backend.SvgToPoints import *

st.title("Lissajous Curve")
st.write(
    '''
    Lissajous curves are fascinating mathematical curves that arise from the superposition of two
      perpendicular harmonic motions. They are named after Jules Antoine Lissajous, a French physicist
        who studied the phenomenon in the 19th century. Lissajous curves can be graphically
          represented and exhibit beautiful patterns, often resembling intricate and mesmerizing
            loops, ovals, or spirals.

    These curves are commonly generated by plotting the x and y coordinates of a point that moves
    in a plane according to two sinusoidal functions with different frequencies and phases. The
    resulting pattern depends on the frequency ratio between the two motions, and various ratios
        create distinct Lissajous figures.

    Lissajous curves have applications in physics, engineering, and art. They are used to study
    and visualize waveforms, analyze signals in electrical circuits, calibrate oscilloscopes,
    and create aesthetically pleasing visual designs. Their intricate and harmonious patterns
        make them a popular subject in mathematics and a source of artistic inspiration.
    '''
)

Moda = st.slider("Pick Value for a", 1, 10, 3, key = "<one>")
Modb = st.slider("Pick Value for b", 1, 10, 3, key = "<two>")
t = np.linspace(-1, 1, num=100, endpoint=True)

x=np.sin(Moda*t)
y=np.sin(Modb*t)

figure, axes = plt.subplots()
plt.xticks([])
plt.yticks([])
axes.plot(x,y)

c1, c2 = st.columns([9, 1])
clicked=False
points=[]
with c2:
    ''
    ''
    ''
    if st.button('Print'):
        clicked=True
        figure.savefig('SVG/Lissajous.svg', format='svg', dpi=100)
        points=getPoints('SVG/Lissajous.svg')
        st.balloons()

with c1:
    if clicked:
        axes.scatter(x[0], y[0], c='red', zorder=100)
        axes.text(x[0]-0.08, y[0]-0.12, 'Start', fontsize=12, zorder=101)
    st.write(figure)

if clicked:
    st.header('The Path being Printed')
    st.write('''Below are the points constituting the path(s) being transmitted to the robot, starting from the red dot.
            The line(s) corresponds to the ideal pattern or path(s) that should be followed to reproduce the desired drawing.
            However, due to the robot's linear interpolation between the points, there may be slight discrepancies
            between the exact pattern and the actual drawing.''')
    # Plot points
    fig, ax = plt.subplots()
    plt.xticks([])
    plt.yticks([])
    for path in points:
        x, y = zip(*path)
        ax.plot(x, y)
        ax.scatter(x, y)
    ax.scatter(x[0], y[0], c='red', zorder=10)
    ax.set_aspect('equal')
    st.pyplot(fig)

st.subheader('References')
st.write('''
- https://www.testandmeasurementtips.com/using-scope-display-lissajous-patterns/#:~:text=When%20the%20oscilloscope%20is%20operating,known%20as%20a%20Lissajous%20pattern.
''')